// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SportManagementSystem.Data;

#nullable disable

namespace SportManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260214151228_AddImagesTables")]
    partial class AddImagesTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "e_account_status", new[] { "active", "suspended", "inactive" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "e_booking_status", new[] { "booked", "attended", "canceled", "no_show" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "e_equipment_condition", new[] { "new", "good", "need_repair", "broken" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "e_iso_currency", new[] { "aed", "afn", "all", "amd", "ang", "aoa", "ars", "aud", "awg", "azn", "bam", "bbd", "bdt", "bgn", "bhd", "bif", "bmd", "bnd", "bob", "brl", "bsd", "btn", "bwp", "byn", "bzd", "cad", "cdf", "chf", "clp", "cny", "cop", "crc", "cuc", "cup", "cve", "czk", "djf", "dkk", "dop", "dzd", "egp", "ern", "etb", "eur", "fjd", "fkp", "gbp", "gel", "ggp", "ghs", "gip", "gmd", "gnf", "gtq", "gyd", "hkd", "hnl", "hrk", "htg", "huf", "idr", "ils", "imp", "inr", "iqd", "irr", "isk", "jep", "jmd", "jod", "jpy", "kes", "kgs", "khr", "kmf", "kpw", "krw", "kwd", "kyd", "kzt", "lak", "lbp", "lkr", "lrd", "lsl", "lyd", "mad", "mdl", "mga", "mkd", "mmk", "mnt", "mop", "mru", "mur", "mvr", "mwk", "mxn", "myr", "mzn", "nad", "ngn", "nio", "nok", "npr", "nzd", "omr", "pab", "pen", "pgk", "php", "pkr", "pln", "pyg", "qar", "ron", "rsd", "rub", "rwf", "sar", "sbd", "scr", "sdg", "sek", "sgd", "shp", "sll", "sos", "srd", "ssp", "stn", "svc", "syp", "szl", "thb", "tjs", "tmt", "tnd", "top", "try", "ttd", "twd", "tzs", "uah", "ugx", "usd", "uyu", "uzs", "ves", "vnd", "vuv", "wst", "xaf", "xcd", "xdr", "xof", "xpf", "yer", "zar", "zmw", "zwl" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "e_membership_status", new[] { "active", "expired", "frozen" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "e_notification_status", new[] { "pending", "send", "failed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "e_room_status", new[] { "available", "maintenance", "closed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "e_service_category", new[] { "training", "massage", "sauna", "fitness", "other" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "e_session_status", new[] { "planned", "done", "canceled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "e_user_role", new[] { "admin", "manager", "trainer", "cashier", "client" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SportManagementSystem.Modules.Assets.Domain.Entities.DbBranch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("SportManagementSystem.Modules.Assets.Domain.Entities.DbEquipment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("Condition")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("SportManagementSystem.Modules.Assets.Domain.Entities.DbRoom", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("SportManagementSystem.Modules.Clients.Domain.Entities.DbBooking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Booked")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("SessionId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("SportManagementSystem.Modules.Clients.Domain.Entities.DbMembership", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int?>("RemainingVisits")
                        .HasColumnType("integer");

                    b.Property<long>("SportServiceId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TotalVisits")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("SportServiceId");

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("SportManagementSystem.Modules.Images.Domain.Entities.DbImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DbBranchId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DbEquipmentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DbRoomId")
                        .HasColumnType("bigint");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Length")
                        .HasColumnType("bigint");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DbBranchId");

                    b.HasIndex("DbEquipmentId");

                    b.HasIndex("DbRoomId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("SportManagementSystem.Modules.Scheduling.Domain.Entities.DbServiceSchedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<long?>("RoomId")
                        .HasColumnType("bigint");

                    b.Property<long>("SportServiceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("StaffId")
                        .HasColumnType("bigint");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("SportServiceId");

                    b.HasIndex("StaffId");

                    b.ToTable("ServiceSchedules");
                });

            modelBuilder.Entity("SportManagementSystem.Modules.Scheduling.Domain.Entities.DbTrainingSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("EndedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ScheduleId")
                        .HasColumnType("bigint");

                    b.Property<long>("SportServiceId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("TrainerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("SportServiceId");

                    b.HasIndex("TrainerId");

                    b.ToTable("TrainingSessions");
                });

            modelBuilder.Entity("SportManagementSystem.Modules.Services.Domain.Entities.DbServicePrice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<long>("SportServiceId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("SportServiceId");

                    b.ToTable("ServicePrices");
                });

            modelBuilder.Entity("SportManagementSystem.Modules.Services.Domain.Entities.DbSportService", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("SportServices");
                });

            modelBuilder.Entity("SportManagementSystem.Modules.Users.Domain.Entities.DbClient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("AvatarId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Patronymic")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("SportManagementSystem.Modules.Users.Domain.Entities.DbStaff", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("AvatarId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<long>("BranchId1")
                        .HasColumnType("bigint");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.HasIndex("BranchId1");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("SportManagementSystem.Modules.Users.Domain.Entities.DbUserAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<long?>("StaffId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("StaffId");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("SportManagementSystem.Modules.Assets.Domain.Entities.DbEquipment", b =>
                {
                    b.HasOne("SportManagementSystem.Modules.Assets.Domain.Entities.DbRoom", "Room")
                        .WithMany("Equipments")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SportManagementSystem.Modules.Assets.Domain.Entities.DbRoom", b =>
                {
                    b.HasOne("SportManagementSystem.Modules.Assets.Domain.Entities.DbBranch", "Branch")
                        .WithMany("Rooms")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("SportManagementSystem.Modules.Clients.Domain.Entities.DbBooking", b =>
                {
                    b.HasOne("SportManagementSystem.Modules.Users.Domain.Entities.DbClient", "Client")
                        .WithMany("Bookings")
                        .HasForeignKey("ClientId");

                    b.HasOne("SportManagementSystem.Modules.Scheduling.Domain.Entities.DbTrainingSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SportManagementSystem.Modules.Clients.Domain.Entities.DbMembership", b =>
                {
                    b.HasOne("SportManagementSystem.Modules.Users.Domain.Entities.DbClient", "Client")
                        .WithMany("Memberships")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportManagementSystem.Modules.Services.Domain.Entities.DbSportService", "SportService")
                        .WithMany()
                        .HasForeignKey("SportServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("SportService");
                });

            modelBuilder.Entity("SportManagementSystem.Modules.Images.Domain.Entities.DbImage", b =>
                {
                    b.HasOne("SportManagementSystem.Modules.Assets.Domain.Entities.DbBranch", null)
                        .WithMany("Images")
                        .HasForeignKey("DbBranchId");

                    b.HasOne("SportManagementSystem.Modules.Assets.Domain.Entities.DbEquipment", null)
                        .WithMany("Images")
                        .HasForeignKey("DbEquipmentId");

                    b.HasOne("SportManagementSystem.Modules.Assets.Domain.Entities.DbRoom", null)
                        .WithMany("Images")
                        .HasForeignKey("DbRoomId");
                });

            modelBuilder.Entity("SportManagementSystem.Modules.Scheduling.Domain.Entities.DbServiceSchedule", b =>
                {
                    b.HasOne("SportManagementSystem.Modules.Assets.Domain.Entities.DbRoom", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId");

                    b.HasOne("SportManagementSystem.Modules.Services.Domain.Entities.DbSportService", "SportService")
                        .WithMany()
                        .HasForeignKey("SportServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportManagementSystem.Modules.Users.Domain.Entities.DbStaff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId");

                    b.Navigation("Room");

                    b.Navigation("SportService");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("SportManagementSystem.Modules.Scheduling.Domain.Entities.DbTrainingSession", b =>
                {
                    b.HasOne("SportManagementSystem.Modules.Scheduling.Domain.Entities.DbServiceSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId");

                    b.HasOne("SportManagementSystem.Modules.Services.Domain.Entities.DbSportService", "SportService")
                        .WithMany()
                        .HasForeignKey("SportServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportManagementSystem.Modules.Users.Domain.Entities.DbStaff", "Trainer")
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");

                    b.Navigation("SportService");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("SportManagementSystem.Modules.Services.Domain.Entities.DbServicePrice", b =>
                {
                    b.HasOne("SportManagementSystem.Modules.Services.Domain.Entities.DbSportService", "SportService")
                        .WithMany("Prices")
                        .HasForeignKey("SportServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SportService");
                });

            modelBuilder.Entity("SportManagementSystem.Modules.Users.Domain.Entities.DbClient", b =>
                {
                    b.HasOne("SportManagementSystem.Modules.Images.Domain.Entities.DbImage", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId");

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("SportManagementSystem.Modules.Users.Domain.Entities.DbStaff", b =>
                {
                    b.HasOne("SportManagementSystem.Modules.Images.Domain.Entities.DbImage", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId");

                    b.HasOne("SportManagementSystem.Modules.Assets.Domain.Entities.DbBranch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avatar");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("SportManagementSystem.Modules.Users.Domain.Entities.DbUserAccount", b =>
                {
                    b.HasOne("SportManagementSystem.Modules.Users.Domain.Entities.DbClient", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("SportManagementSystem.Modules.Users.Domain.Entities.DbStaff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId");

                    b.Navigation("Client");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("SportManagementSystem.Modules.Assets.Domain.Entities.DbBranch", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("SportManagementSystem.Modules.Assets.Domain.Entities.DbEquipment", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("SportManagementSystem.Modules.Assets.Domain.Entities.DbRoom", b =>
                {
                    b.Navigation("Equipments");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("SportManagementSystem.Modules.Services.Domain.Entities.DbSportService", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("SportManagementSystem.Modules.Users.Domain.Entities.DbClient", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
