networks:
  backend:
    driver: bridge

volumes:
  postgres_database:

services:
  sportmanagementsystem:
    image: sportmanagementsystem
    build:
      context: .
      dockerfile: SportManagementSystem/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:18.1
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'sport_management'
    networks:
      - backend
    ports:
      - "50000:5432"
    volumes:
      - postgres_database:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10